### ISSUE TITLE
Can't find 'download missing lyrics' (again)

### ISSUE THREAD

**Issue by elios93** [Felitendo/jellyfin-lyrics-plugin#10]
Sorry to bother you talking about an already treated subject, however I've tried to do all given suggestions but nothing seems to work. I have the jellyfin server installed on a raspberry pi 5, version 10.9.11. I already changed the repository with the updated one, tried to reinstall the plugin but still get version 0.0.0.0 and no 'download missing lyrics' option available. How can I get rid of the issue? To be noticed that to uninstall the plugin I have to manually delete the folder in /var/lib/jellyfin/plugins. I have to clear other directory to get a clean installation? Thank you in advance.

**Comment by Felitendo** [comment]
The only way to fix this would be a full reinstall of jellyfin. I haven't found any other way to fix that as of now :/

**Comment by elios93** [comment]
Thank you for the fast reply! After many attempts, I tried to reboot my whole device and everything worked as expected. I hope that this can help other people with the same problem. 
@Felitendo thank you for your great work!

**Comment by Felitendo** [comment]
I'm very happy that it works for you now :D
