### ISSUE TITLE
Can't find 'Download missing lyrics'

### ISSUE THREAD

**Issue by Felitendo** [Felitendo/jellyfin-lyrics-plugin#2]
Issue from @EsmailELBoBDev2:

Hello I just installed this *but sadly I can't find 'Download missing lyrics' in tasks...I'm using 10.9.11 too but not so fresh install if being honest, it runs for some weeks now

**Comment by EsmailELBoBDev2** [comment]
yup im here

**Comment by Felitendo** [comment]
Hey, could you please check if you deleted the old LrcLib Plugin before installing this one?
Also are you hosting your Jellyfin instance on Windows or on Linux via Docker?

**Comment by EsmailELBoBDev2** [comment]
I never installed it before and I'm hosting it on linux via docker compose yes

**Comment by Felitendo** [comment]
That's weird. I have tried it yesterday and it worked just fine on a new install.
Could you maybe try to restart your jellyfin?
Also what Version does Jellyfin show for the Plugin? Is it 0.0.0.0 or 1.0.0.0?

**Comment by EsmailELBoBDev2** [comment]
> That's weird. I have tried it yesterday and it worked just fine on a new install. Could you maybe try to restart your jellyfin? Also what Version does Jellyfin show for the Plugin? Is it 0.0.0.0 or 1.0.0.0?

Sorry for late reply and I restarted it, in repo of plugins it shows to install 1.0.0.0 but when actually installed I get 0.0.0.0 showed

**Comment by Felitendo** [comment]
It has to show 1.0.0.0, otherwise it won't work

**Comment by EsmailELBoBDev2** [comment]
> It has to show 1.0.0.0, otherwise it won't work

but how to do it, I selected it from drop menu (which is only selection) but when I click install I get 0.0.0.0 version. and again it's first time on new install so why would be that? I used `https://raw.githubusercontent.com/crobibero/jellyfin-plugin-lrclib/master/manifest.json` for the repo

**Comment by EsmailELBoBDev2** [comment]
Okay when I add it it marks as 1.0.0.0 but when I actually restart jellyfin the version appear as 0.0.0.0 and in files it's 1.0.0.0 so it's either display issue or for whatever reason jellyfin downgrades it

**Comment by EsmailELBoBDev2** [comment]
Okay it works!! but still marked as 0.0.0.0 in installed plugins...

**Comment by Felitendo** [comment]
> > It has to show 1.0.0.0, otherwise it won't work
> 
> but how to do it, I selected it from drop menu (which is only selection) but when I click install I get 0.0.0.0 version. and again it's first time on new install so why would be that? I used `https://raw.githubusercontent.com/crobibero/jellyfin-plugin-lrclib/master/manifest.json` for the repo
> 
> Maybe I get this because in manifest.json:
> 
> ```
>                 "targetAbi": "10.9.0.0",
> ```
> 
> And I use 10.9.11
> 
> Edit: nvm I saw you installed it on 10.9.11 too, but not sure why it does not show with me. is there specific location for logs I can look for or something to do to force it to be 1.0.0.0

Ohhh I know why. You need to use https://raw.githubusercontent.com/Felitendo/jellyfin-lyrics-plugin/master/manifest.json for the repo.

**Comment by Felitendo** [comment]
Always read the install instructions in the README please:
https://github.com/Felitendo/jellyfin-lyrics-plugin?tab=readme-ov-file#-installation

**Comment by Felitendo** [comment]
If it shows the Version 0.0.0.0 even though it's working correctly, then just ignore it

**Comment by EsmailELBoBDev2** [comment]
> Always read the install instructions in the README please: https://github.com/Felitendo/jellyfin-lyrics-plugin?tab=readme-ov-file#-installation

in fairness the readme updated after i reported the issue and thanks for help

**Comment by Felitendo** [comment]
You're right. I probably should have made the readme earlier on. But better late then never I guess. I'm glad I could help you :)

**Comment by EsmailELBoBDev2** [comment]
It's okay and thanks for the amazing project I really like it.
